SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
CREATE DATABASE IF NOT EXISTS `onlineDB`;
USE `onlineDB`;
CREATE TABLE IF NOT EXISTS `user`(
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(255) NOT NULL ,
  `pass` VARCHAR(2000) NOT NULL,
  `user_image` LONGBLOB NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`user_id`),
  UNIQUE KEY(`user`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
COMMIT;
